version: '3'
services:
  db:
    image: mysql:8.0.33
    container_name: spot-db
    restart: always
    ports:
      - "3306:3306"
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ./mysql-init-files/:/docker-entrypoint-initdb.d
  redis:
    image: redis
    container_name: spot-redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${SPRING_DATA_REDIS_PASSWORD}
  server:
    image: dltmdals6718/spot-server
    container_name: spot-server
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/spot
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATA_REDIS_HOST: ${SPRING_DATA_REDIS_HOST}
      SPRING_DATA_REDIS_PASSWORD: ${SPRING_DATA_REDIS_PASSWORD}
      SPRING_DATA_REDIS_PORT: ${SPRING_DATA_REDIS_PORT}
    volumes:
      - /home/ubuntu/docker/logs:/logs
    depends_on:
      - db
      - redis